version = 1

[[annotations]]
path = "Resources/*.jpg"
SPDX-FileCopyrightText = "2026 Kaito Udagawa <umireon@kaito.tokyo>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "Resources/font-license.txt"
SPDX-FileCopyrightText = "2026 Kaito Udagawa <umireon@kaito.tokyo>"
SPDX-License-Identifier = "CC0-1.0"
